[package]
name = "our_git"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.6", features = ["derive"] }
digest = "0.10.7"
flate2 = "1.0.30"
hex = "0.4.3"
indexmap = "2.2.6"
regex = "1.10.4"
rust-ini = "0.21.0"
sha1 = "0.10.6"
